-- AddForeignKey
ALTER TABLE `Game` ADD FOREIGN KEY (`teamId`) REFERENCES `Team`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Mission` ADD FOREIGN KEY (`teamId`) REFERENCES `Team`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Mission` ADD FOREIGN KEY (`assignTo`) REFERENCES `Player`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
