name: Deploy cast app to production
on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

defaults:
  run:
    working-directory: cast-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn generate
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: cast-app/dist
  deploy-pwa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: cast-app/dist
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: cast-app/dist/
          remote_path: ~/sites/toodoo/boss/
          remote_host: ${{ secrets.PROD_HOST }}
          remote_port: ${{ secrets.PROD_PORT }}
          remote_user: ${{ secrets.PROD_USERNAME }}
          remote_key: ${{ secrets.PROD_KEY }}
